package com.lumina.nutrition.core.designsystem

import androidx.compose.ui.graphics.Color

val LuminaSurface = Color(0xFFF8FAF9)
val LuminaSurfaceDim = Color(0xFFD8DADA)
val LuminaSurfaceBright = Color(0xFFF8FAF9)
val LuminaSurfaceContainerLowest = Color(0xFFFFFFFF)
val LuminaSurfaceContainerLow = Color(0xFFF2F4F3)
val LuminaSurfaceContainer = Color(0xFFECEEED)
val LuminaSurfaceContainerHigh = Color(0xFFE6E9E8)
val LuminaSurfaceContainerHighest = Color(0xFFE1E3E2)
val LuminaOnSurface = Color(0xFF191C1C)
val LuminaOnSurfaceVariant = Color(0xFF404943)
val LuminaInverseSurface = Color(0xFF2E3131)
val LuminaInverseOnSurface = Color(0xFFEFF1F0)
val LuminaSurfaceTint = Color(0xFF2C694E)
val LuminaBackground = Color(0xFFF8FAF9)
val LuminaOnBackground = Color(0xFF191C1C)
val LuminaSurfaceVariant = Color(0xFFE1E3E2)

val LuminaPrimary = Color(0xFF0F5238)
val LuminaOnPrimary = Color(0xFFFFFFFF)
val LuminaPrimaryContainer = Color(0xFF2D6A4F)
val LuminaOnPrimaryContainer = Color(0xFFA8E7C5)
val LuminaInversePrimary = Color(0xFF95D4B3)
val LuminaPrimaryFixed = Color(0xFFB1F0CE)
val LuminaPrimaryFixedDim = Color(0xFF95D4B3)
val LuminaOnPrimaryFixed = Color(0xFF002114)
val LuminaOnPrimaryFixedVariant = Color(0xFF0E5138)

val LuminaSecondary = Color(0xFF2B694D)
val LuminaOnSecondary = Color(0xFFFFFFFF)
val LuminaSecondaryContainer = Color(0xFFB0F1CC)
val LuminaOnSecondaryContainer = Color(0xFF327053)
val LuminaSecondaryFixed = Color(0xFFB0F1CC)
val LuminaSecondaryFixedDim = Color(0xFF94D4B1)
val LuminaOnSecondaryFixed = Color(0xFF002113)
val LuminaOnSecondaryFixedVariant = Color(0xFF0C5136)

val LuminaTertiary = Color(0xFF313C9F)
val LuminaOnTertiary = Color(0xFFFFFFFF)
val LuminaTertiaryContainer = Color(0xFF4A55B9)
val LuminaOnTertiaryContainer = Color(0xFFD5D7FF)
val LuminaTertiaryFixed = Color(0xFFDFE0FF)
val LuminaTertiaryFixedDim = Color(0xFFBDC2FF)
val LuminaOnTertiaryFixed = Color(0xFF000866)
val LuminaOnTertiaryFixedVariant = Color(0xFF303B9F)

val LuminaError = Color(0xFFBA1A1A)
val LuminaOnError = Color(0xFFFFFFFF)
val LuminaErrorContainer = Color(0xFFFFDAD6)
val LuminaOnErrorContainer = Color(0xFF93000A)

val LuminaOutline = Color(0xFF707973)
val LuminaOutlineVariant = Color(0xFFBFC9C1)
