package com.kcalgrindai.app.core.designsystem

import androidx.compose.ui.graphics.Color

val KcalGrindSurface = Color(0xFFF8FAF9)
val KcalGrindSurfaceDim = Color(0xFFD8DADA)
val KcalGrindSurfaceBright = Color(0xFFF8FAF9)
val KcalGrindSurfaceContainerLowest = Color(0xFFFFFFFF)
val KcalGrindSurfaceContainerLow = Color(0xFFF2F4F3)
val KcalGrindSurfaceContainer = Color(0xFFECEEED)
val KcalGrindSurfaceContainerHigh = Color(0xFFE6E9E8)
val KcalGrindSurfaceContainerHighest = Color(0xFFE1E3E2)
val KcalGrindOnSurface = Color(0xFF191C1C)
val KcalGrindOnSurfaceVariant = Color(0xFF404943)
val KcalGrindInverseSurface = Color(0xFF2E3131)
val KcalGrindInverseOnSurface = Color(0xFFEFF1F0)
val KcalGrindSurfaceTint = Color(0xFF2C694E)
val KcalGrindBackground = Color(0xFFF8FAF9)
val KcalGrindOnBackground = Color(0xFF191C1C)
val KcalGrindSurfaceVariant = Color(0xFFE1E3E2)

val KcalGrindPrimary = Color(0xFF0F5238)
val KcalGrindOnPrimary = Color(0xFFFFFFFF)
val KcalGrindPrimaryContainer = Color(0xFF2D6A4F)
val KcalGrindOnPrimaryContainer = Color(0xFFA8E7C5)
val KcalGrindInversePrimary = Color(0xFF95D4B3)
val KcalGrindPrimaryFixed = Color(0xFFB1F0CE)
val KcalGrindPrimaryFixedDim = Color(0xFF95D4B3)
val KcalGrindOnPrimaryFixed = Color(0xFF002114)
val KcalGrindOnPrimaryFixedVariant = Color(0xFF0E5138)

val KcalGrindSecondary = Color(0xFF2B694D)
val KcalGrindOnSecondary = Color(0xFFFFFFFF)
val KcalGrindSecondaryContainer = Color(0xFFB0F1CC)
val KcalGrindOnSecondaryContainer = Color(0xFF327053)
val KcalGrindSecondaryFixed = Color(0xFFB0F1CC)
val KcalGrindSecondaryFixedDim = Color(0xFF94D4B1)
val KcalGrindOnSecondaryFixed = Color(0xFF002113)
val KcalGrindOnSecondaryFixedVariant = Color(0xFF0C5136)

val KcalGrindTertiary = Color(0xFF313C9F)
val KcalGrindOnTertiary = Color(0xFFFFFFFF)
val KcalGrindTertiaryContainer = Color(0xFF4A55B9)
val KcalGrindOnTertiaryContainer = Color(0xFFD5D7FF)
val KcalGrindTertiaryFixed = Color(0xFFDFE0FF)
val KcalGrindTertiaryFixedDim = Color(0xFFBDC2FF)
val KcalGrindOnTertiaryFixed = Color(0xFF000866)
val KcalGrindOnTertiaryFixedVariant = Color(0xFF303B9F)

val KcalGrindError = Color(0xFFBA1A1A)
val KcalGrindOnError = Color(0xFFFFFFFF)
val KcalGrindErrorContainer = Color(0xFFFFDAD6)
val KcalGrindOnErrorContainer = Color(0xFF93000A)

val KcalGrindOutline = Color(0xFF707973)
val KcalGrindOutlineVariant = Color(0xFFBFC9C1)
